- name: Commit & push (rebase-safe)
  env:
    BRANCH: ${{ github.ref_name }}   # biasanya "main"
  run: |
    set -e
    # tidak ada perubahan? selesai
    if git diff --quiet -- news.json data/news_prev.json; then
      echo "No changes"; exit 0
    fi

    git config user.name  "github-actions[bot]"
    git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

    git add news.json data/news_prev.json
    git commit -m "chore: refresh news.json [skip ci]" || true

    # tarik perubahan terbaru lalu rebase commit kita di atasnya
    git fetch origin "$BRANCH"
    git pull --rebase --autostash origin "$BRANCH"

    # dorong ke branch yang sama
    git push origin HEAD:"$BRANCH"
