name: Build News JSON

on:
  workflow_dispatch: {}
  schedule:
    # UTC: 02:05 & 14:05  → WIB: 09:05 & 21:05
    - cron: '5 2,14 * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm i rss-parser@3

      - name: Build news.json
        run: node tools/rss-build.mjs

      - name: Commit & push if changed
        run: |
          if git diff --quiet -- news.json; then
            echo "No changes"
          else
            git config user.name  "sumberfakta-bot"
            git config user.email "bot@users.noreply.github.com"
            git add news.json data/news_prev.json || true
            git commit -m "chore: refresh news.json [skip ci]"
            git push
          fi
